### ISSUE TITLE
would like to contribute an example of using Fmt to format JSON

### ISSUE THREAD

**Issue by chetmurthy** [dbuenzli/fmt#36] opened 2019-04-03 16:20 UTC
Should I just paste the example in this issue?  Or send you a PR?  It's small, and my motivation is mostly that there aren't any examples that come with Fmt, and that seems to be the biggest impediment to using it.

**Comment by dbuenzli** [comment] 2019-04-03 17:33
PR is better so that you can update it if I have comments. 

I suggest you add it at the end of the `Fmt.mli` in a dedicated "Examples" section. See for example https://b0-system.github.io/odig/doc/jsonm/Jsonm/index.html

**Comment by chetmurthy** [comment] 2019-04-03 18:04
Daniel, this sounds like an excellent idea, but .... I've never actually *run* ocamldoc, and having tried to do so on both your jsonm and fmt projects, am mystified as to how it works.  The opam build process doesn't seem to generate documentation -- could you point me at how to do so?  Sorry, this is *literally* the first time I've tried to actually generate doc (I usually just read the MLI file directly).  I'm aware that the documentation is structured, and obviously I'd like to respect that and write something that fits in with the rest of your code.

**Comment by dbuenzli** [comment] 2019-04-03 18:20
This should do:
```
opam install topkg-care
git clone https://github.com/dbuenzli/fmt.git
cd fmt
topkg doc -r 
```

**Comment by dbuenzli** [comment] 2019-06-21 11:58
Not a bug so closing this. Feel free to PR anything you may come up with.

**Closed by dbuenzli** 2019-06-21 11:58 UTC
Labels: invalid

**Comment by chetmurthy** [comment] 2019-06-21 18:04
Hey, sorry, I still haven't had the time to learn how to properly format structured comments in Ocaml.  Hopefully I'll have time soon and send you a PR.
