### ISSUE TITLE
Error,Bug in Install fmt!

### ISSUE THREAD

**Issue by questionpython** [dbuenzli/fmt#22] opened 2017-04-07 07:23 UTC
$ opam install fmt
```
The following actions will be performed:
  ∗  install fmt 0.8.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[fmt] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of fmt failed at "ocaml pkg/pkg.ml build --dev-pkg false --with-base-unix true --with-cmdliner true".

#=== ERROR while installing fmt.0.8.2 =========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/pkg.ml build --dev-pkg false --with-base-unix true --with-cmdliner true
# path         /home/guest/.opam/system/build/fmt.0.8.2
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/guest/.opam/system/build/fmt.0.8.2/fmt-17344-6d07ae.env
# stdout-file  /home/guest/.opam/system/build/fmt.0.8.2/fmt-17344-6d07ae.out
# stderr-file  /home/guest/.opam/system/build/fmt.0.8.2/fmt-17344-6d07ae.err
### stderr ###
# pkg.ml: [ERROR] key --dev-pkg: Unknown key.



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install fmt 0.8.2
No changes have been performed
```
$ opam install base-unix cmdliner fmt
```
[NOTE] Package base-unix is already installed (current version is base).
[NOTE] Package cmdliner is already installed (current version is 1.0.0).
The following actions will be performed:
  ∗  install fmt 0.8.2
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[fmt] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of fmt failed at "ocaml pkg/pkg.ml build --dev-pkg false --with-base-unix true --with-cmdliner true".

#=== ERROR while installing fmt.0.8.2 =========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/pkg.ml build --dev-pkg false --with-base-unix true --with-cmdliner true
# path         /home/guest/.opam/system/build/fmt.0.8.2
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/guest/.opam/system/build/fmt.0.8.2/fmt-17402-6d07ae.env
# stdout-file  /home/guest/.opam/system/build/fmt.0.8.2/fmt-17402-6d07ae.out
# stderr-file  /home/guest/.opam/system/build/fmt.0.8.2/fmt-17402-6d07ae.err
### stderr ###
# pkg.ml: [ERROR] key --dev-pkg: Unknown key.



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install fmt 0.8.2
No changes have been performed
```

how fix ?

**Comment by dbuenzli** [comment] 2017-04-07 07:43
Are you sure your packages are up-to-date ? It seems that you don't have the correct version of `topkg`, which is a bit odd since it is [correctly constrained](https://github.com/ocaml/opam-repository/blob/master/packages/fmt/fmt.0.8.2/opam#L17) in the repo. 

Could you please tell me what the following invocations output: 

```
opam info topkg -f version
opam config report 
```

May simply doing a:

```
opam upgrade
opam install fmt
```
will fix things.

**Comment by dbuenzli** [comment] 2017-04-10 18:02
Closing this since I can't reproduce. Please report if you solved the issue or provide more details if that's not the case.

**Closed by dbuenzli** 2017-04-10 18:02 UTC
